.github/workflows/publish.yml
README.md
packages/components/button/package.json
packages/svg-icons/package.json

This PR adds extra configs to enable publishing the packages.

build: add extra publish configs

---

.github/workflows/publish.yml
packages/components/button/CHANGELOG.md
packages/components/button/package.json
packages/svg-icons/CHANGELOG.md
packages/svg-icons/package.json

Reset version to 0 after testing the publish.

refactor: reset versions [skip ci]

---

packages/react/README.md
packages/react/package.json
packages/react/src/hooks/DarkMode.tsx
packages/react/src/hooks/index.ts
packages/react/src/index.ts
packages/react/tsconfig.json
packages/react/tsconfig.release.json
packages/react/vite.config.ts
yarn.lock

Created a new react package to host all the configs for the Design System

refactor: create a react configs package

---

.github/workflows/publish.yml

This pull request adds git checkout into the publish workflow to force the checkout into the reference branch providing the correct context to lerna.

ci: add git checkout to publish workflow

---

package.json

Add no verify to github actions to avoid lerna to authenticate and return a 401 error.

ci: add no verify to github actions

---

.github/workflows/publish.yml
package.json

ci: update workflow

---

packages/components/button/src/button.styles.ts

feat: publish test

---

packages/components/button/src/button.styles.ts

Reverts Douro-ui/design-system#10

Revert "feat: publish test"

---

.github/workflows/publish.yml

ci: add new publish workflow

---

packages/components/button/src/Button.tsx

feat: new feat test

---

.github/workflows/publish.yml

ci: add git configs

---

packages/components/button/src/Button.tsx

feat: test

---

packages/react/src/context/ThemeProvider.tsx

feat: test workflow

---

packages/react/src/context/ThemeProvider.tsx

fix: test react bump version

---

packages/react/src/context/ThemeProvider.tsx

fix: permissions for non bot users

---

packages/react/package.json
packages/react/src/context/GlobalStyles.tsx
packages/react/src/context/index.ts
yarn.lock

feat: create a global style with resets

---

packages/react/src/context/ThemeProvider.tsx
packages/react/src/context/__tests__/ThemeProvider.spec.tsx
packages/react/src/hooks/index.ts
packages/react/src/hooks/useTheme.ts
packages/react/src/index.ts
packages/react/src/tokens/index.ts
packages/react/src/tokens/palettes/index.ts
packages/react/src/tokens/palettes/palette.ts
packages/react/src/tokens/themes/index.ts
packages/react/src/tokens/themes/theme.constants.ts
packages/react/src/tokens/themes/theme.ts
packages/react/src/tokens/themes/theme.types.ts

Add the default theme and the color palletes. Adjustment to themeProvider. Fix the themeProvider test

feat: create a default theme

---

.stylelintrc.json
README.md
package.json
packages/components/button/src/button.styles.ts
yarn.lock

Add stylelint configs and some rules to prevent style issues.

build: add stylelint and few rules [skip ci]

---

packages/components/radio/src/Radio.tsx
packages/components/radio/src/RadioGroup.stories.tsx
packages/components/radio/src/RadioGroup.tsx
packages/components/radio/src/__tests__/Radio.spec.tsx
packages/components/radio/src/__tests__/RadioGroup.spec.tsx
packages/components/radio/src/index.ts
packages/components/radio/src/radio.styles.ts
packages/components/radio/src/radio.types.ts

This update addresses the need for a customizable and reusable set of radio button components in the project.

feat: radio component

---

README.md

Add Installation process to Readme file.

docs: add installation to readme

---

packages/components/radio/src/radio.styles.ts

Disable style lint on the theme file temporarily so we can do PRs normally

chore: temporarily disable stylelint on the theme file

---

packages/components/checkbox/README.md
packages/components/checkbox/package.json
packages/components/checkbox/src/Checkbox.tsx
packages/components/checkbox/src/CheckboxGroup.stories.tsx
packages/components/checkbox/src/CheckboxGroup.tsx
packages/components/checkbox/src/__tests__/Checkbox.spec.tsx
packages/components/checkbox/src/__tests__/CheckboxGroup.spec.tsx
packages/components/checkbox/src/checkbox.styles.ts
packages/components/checkbox/src/checkbox.types.ts
packages/components/checkbox/src/index.ts
packages/components/checkbox/tsconfig.json
packages/components/checkbox/tsconfig.release.json
packages/components/checkbox/vite.config.ts
packages/components/radio/src/index.ts

feat: checkbox component

---

packages/components/checkbox/package.json
packages/components/checkbox/vite.config.ts

Force checkbox publish because the first attempt failed and the publish didn't work after retrying.
https://github.com/Douro-ui/design-system/actions/runs/9778012184/attempts/1

feat: force checkout publish

---

package.json
packages/components/radio/src/RadioGroup.stories.tsx

This PR includes component tests for storybook component radioGroup. The tests are using storybook test runner validate the renderization of each story from storybook and also implement a play function to validate interactions with the component.
https://storybook.js.org/blog/test-component-interactions-with-storybook/

test: adding components tests - RadioGroup

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
package.json
packages/components/checkbox/src/Checkbox.tsx
packages/components/checkbox/src/CheckboxGroup.stories.tsx
packages/components/checkbox/src/__tests__/Checkbox.spec.tsx
packages/components/checkbox/src/__tests__/CheckboxGroup.spec.tsx
packages/components/checkbox/src/checkbox.types.ts
packages/components/radio/src/__tests__/Radio.spec.tsx
packages/components/radio/src/__tests__/RadioGroup.spec.tsx
packages/react/src/utils/deepMerge.ts
yarn.lock

Include some format fixes and deepmerge change

fix: format and deepMerge 

---

.gitattributes

This fixes the git eol default

fix: git eol

---

packages/components/radio/README.md
packages/components/radio/package.json
packages/components/radio/tsconfig.json
packages/components/radio/tsconfig.release.json
packages/components/radio/vite.config.ts

This fix the radio component in the project.

fix: radio component

---

packages/components/tabs/README.md
packages/components/tabs/package.json
packages/components/tabs/src/Tabs.tsx
packages/components/tabs/src/TabsGroup.stories.tsx
packages/components/tabs/src/TabsGroup.tsx
packages/components/tabs/src/__tests__/Tabs.spec.tsx
packages/components/tabs/src/__tests__/TabsGroup.spec.tsx
packages/components/tabs/src/index.ts
packages/components/tabs/src/tabs.styles.ts
packages/components/tabs/src/tabs.types.ts
packages/components/tabs/tsconfig.json
packages/components/tabs/tsconfig.release.json
packages/components/tabs/vite.config.ts

This update addresses the need for a customizable and reusable set of tabs component in the project.

feat: tabs component

---

packages/components/tabs/src/Tabs.tsx
packages/components/tabs/src/TabsGroup.stories.tsx
packages/components/tabs/src/__tests__/Tabs.spec.tsx
packages/components/tabs/src/__tests__/TabsGroup.spec.tsx
packages/components/tabs/src/tabs.styles.ts
packages/react/src/hooks/useTheme.ts

fix: tabs component

---

.github/workflows/ui-tests.yml
.storybook/main.ts
package.json
packages/components/checkbox/src/CheckboxGroup.stories.tsx
packages/components/radio/src/RadioGroup.stories.tsx

This PR adds tests for checkbox component. Also adds a new addon to analyze UI tests coverage (will monitor the behavior of the coverage addon).

test: checkbox tests

---

.storybook/main.ts
packages/react/src/tokens/palettes/PaletteStory.tsx
packages/react/src/tokens/palettes/palettes.stories.tsx
packages/react/src/tokens/themes/theme.types.ts
packages/react/src/tokens/typography/TypoStory.tsx
packages/react/src/tokens/typography/typo.stories.tsx

files created to preview tokens of typography and colors existent

feat: tokens preview [SKIP CI]

---

.stylelintrc.json
package.json
packages/components/checkbox/src/checkbox.styles.ts
packages/components/radio/src/radio.styles.ts
packages/components/tabs/src/Tabs.tsx
packages/components/tabs/src/TabsGroup.tsx
packages/components/tabs/src/tabs.styles.ts
packages/components/tabs/src/tabs.types.ts
packages/react/src/context/GlobalStyles.tsx
packages/react/src/context/ThemeProvider.tsx
packages/react/src/hooks/useTheme.ts
packages/react/src/tokens/palettes/palette.ts
packages/react/src/tokens/themes/theme.ts
tsconfig.json
yarn.lock

Updated stylelint config file and applied the changes thought the code, alongside it the Tab component is updated

fix:  stylelint & tabs

---

packages/react/src/tokens/palettes/PaletteStory.tsx

this fix is to address the values on pallette that used px.

fix: values with px to theme values

---

packages/components/tabs/src/TabsGroup.stories.tsx

This PR adds tests for Tab component.

test: adding tests for tab component

---

.github/workflows/create-release-pr.yml
.github/workflows/publish.yml
yarn.lock

This PR fixes the dependency problem where sometimes the yarn.lock where recreated

fix: dependencies

---

packages/react/src/context/GlobalStyles.tsx
packages/react/src/context/ThemeProvider.tsx
packages/react/src/theme/index.ts
packages/react/src/utils/__tests__/deepMerge.spec.tsx
packages/react/src/utils/deepMerge.ts

- Forgot to export theme in the root
- Add extra typings to avoid errors.
- Remove partials

fix: theme typings and tsc errors

---

packages/components/link/README.md
packages/components/link/package.json
packages/components/link/src/Link.stories.tsx
packages/components/link/src/Link.tsx
packages/components/link/src/__tests__/Link.spec.tsx
packages/components/link/src/index.ts
packages/components/link/src/link.styles.ts
packages/components/link/src/link.types.ts
packages/components/link/tsconfig.json
packages/components/link/tsconfig.release.json
packages/components/link/vite.config.ts

feat: link component

---

packages/components/link/src/Link.stories.tsx

This PR adds tests for link component. 

test: adding link tests

---

packages/components/button/src/Button.tsx
packages/components/button/src/__tests__/Button.spec.tsx
packages/components/button/src/button.styles.ts
packages/components/button/src/button.types.ts
packages/components/button/src/buttonTypes/ErrorButton.tsx
packages/components/button/src/buttonTypes/PrimaryButton.tsx
packages/components/button/src/buttonTypes/SecondaryButton.tsx
packages/components/button/src/buttonTypes/TertiaryButton.tsx
packages/components/button/src/index.ts
packages/components/link/src/index.ts
packages/components/radio/src/index.ts

- Define fallback for button type avoiding the app to break.
- Also, export default components in the root
- Add styled border-radius

fix: button without props

---

eslint.config.mjs
scripts/dui/templates/component/package.json

Missing template on the package json template file

fix: missing template

---

packages/components/button/src/Button.stories.tsx
scripts/dui/templates/component/src/{{Name}}.stories.tsx.template
tsconfig.json

The event onClick is re-added to button storybook so it can be tested properly on the storybook test side

fix: re-added onClick to button storybook

---

packages/components/button/src/Button.stories.tsx

This PR adds ui interaction and style tests for button component.

test: button ui tests

---

.github/workflows/create-release-pr.yml
package.json
packages/components/button/src/button.styles.ts
packages/components/button/src/buttonTypes/ErrorButton.tsx
packages/components/button/src/buttonTypes/PrimaryButton.tsx
packages/components/button/src/buttonTypes/SecondaryButton.tsx
packages/components/button/src/buttonTypes/TertiaryButton.tsx
packages/components/link/src/Link.tsx
packages/components/link/src/link.styles.ts
packages/components/tabs/src/TabsGroup.tsx
packages/react/src/tokens/palettes/palettes.stories.tsx
packages/react/src/tokens/typography/TypoStory.styles.tsx
packages/react/src/tokens/typography/typo.stories.tsx
tsconfig.json

Fixed issues on styled objects where they were not optional.

fix: linting styled errors

---

packages/components/avatar/README.md
packages/components/avatar/package.json
packages/components/avatar/src/Avatar.stories.tsx
packages/components/avatar/src/Avatar.tsx
packages/components/avatar/src/__tests__/Avatar.spec.tsx
packages/components/avatar/src/avatar.styles.ts
packages/components/avatar/src/avatar.types.ts
packages/components/avatar/src/avatarTypes/BaseAvatar.tsx
packages/components/avatar/src/avatarTypes/ImageAvatar.tsx
packages/components/avatar/src/avatarTypes/index.tsx
packages/components/avatar/src/index.ts
packages/components/avatar/tsconfig.json
packages/components/avatar/tsconfig.release.json
packages/components/avatar/vite.config.ts
scripts/dui/templates/component/vite.config.ts.template

feat: avatar component

---

packages/components/toggle/src/Toggle.stories.tsx

test: storybook tests toogle

---

packages/components/avatar/src/Avatar.stories.tsx

This PR includes tests for avatar component.

 test: avatar ui tests

---

eslint.config.mjs
jest.config.js
package.json
packages/components/carousel/README.md
packages/components/carousel/package.json
packages/components/carousel/src/Carousel.tsx
packages/components/carousel/src/__tests__/Carousel.spec.tsx
packages/components/carousel/src/carousel.stories.ts
packages/components/carousel/src/carousel.styles.ts
packages/components/carousel/src/carousel.types.ts
packages/components/carousel/src/index.ts
packages/components/carousel/tsconfig.json
packages/components/carousel/tsconfig.release.json
packages/components/carousel/vite.config.ts
yarn.lock

this updade addresses the new carousel component. the component accepts images, video, text and custom components.
has infinite loop,  auto-play, and thumbnails.

feat: carousel component

---

packages/components/picture/README.md
packages/components/picture/package.json
packages/components/picture/src/Picture.stories.tsx
packages/components/picture/src/Picture.tsx
packages/components/picture/src/__tests__/Picture.spec.tsx
packages/components/picture/src/index.ts
packages/components/picture/src/picture.styles.ts
packages/components/picture/src/picture.types.ts
packages/components/picture/tsconfig.json
packages/components/picture/tsconfig.release.json
packages/components/picture/vite.config.ts

This update addresses the need for a customizable and reusable set of a picturecomponent in the project.

feat: picture component

---

packages/components/breadcrumb/README.md
packages/components/breadcrumb/package.json
packages/components/breadcrumb/src/Breadcrumb.tsx
packages/components/breadcrumb/src/BreadcrumbGroup.stories.tsx
packages/components/breadcrumb/src/BreadcrumbGroup.tsx
packages/components/breadcrumb/src/__tests__/Breadcrumb.spec.tsx
packages/components/breadcrumb/src/__tests__/BreadcrumbGroup.spec.tsx
packages/components/breadcrumb/src/breadcrumb.styles.ts
packages/components/breadcrumb/src/breadcrumb.types.ts
packages/components/breadcrumb/src/index.ts
packages/components/breadcrumb/tsconfig.json
packages/components/breadcrumb/tsconfig.release.json
packages/components/breadcrumb/vite.config.ts

This update addresses the need for a customizable and reusable set of a breadcrumbs component in the project.

feat: breadcrumbs component

---

packages/components/breadcrumb/src/BreadcrumbGroup.stories.tsx

This PR adds tests for breadcrumb component.

test: breadcrumb ui tests

---

packages/react/src/theme/index.ts

Export constants from theme root

fix: export theme constants

---

packages/components/picture/src/Picture.stories.tsx

This PR adds tests for picture component.

test: picture ui tests

---

packages/components/textarea/README.md
packages/components/textarea/package.json
packages/components/textarea/src/Textarea.stories.tsx
packages/components/textarea/src/Textarea.tsx
packages/components/textarea/src/__tests__/Textarea.spec.tsx
packages/components/textarea/src/index.ts
packages/components/textarea/src/textarea.styles.ts
packages/components/textarea/src/textarea.types.ts
packages/components/textarea/tsconfig.json
packages/components/textarea/tsconfig.release.json
packages/components/textarea/vite.config.ts

This update addresses the need for a customizable and reusable set of a textarea component in the project.

feat: text area component

---

jest.config.js
packages/components/expandablePanel/README.md
packages/components/expandablePanel/package.json
packages/components/expandablePanel/src/ExpandablePanel.stories.tsx
packages/components/expandablePanel/src/ExpandablePanel.tsx
packages/components/expandablePanel/src/__tests__/ExpandablePanel.spec.tsx
packages/components/expandablePanel/src/expandablePanel.styles.ts
packages/components/expandablePanel/src/expandablePanel.types.ts
packages/components/expandablePanel/src/expandablePanelTypes/ExpandablePanelBody.tsx
packages/components/expandablePanel/src/expandablePanelTypes/ExpandablePanelHeader.tsx
packages/components/expandablePanel/src/expandablePanelTypes/index.ts
packages/components/expandablePanel/src/index.ts
packages/components/expandablePanel/tsconfig.json
packages/components/expandablePanel/tsconfig.release.json
packages/components/expandablePanel/vite.config.ts
packages/react/src/hooks/index.ts
packages/react/src/hooks/useHeightDimension.ts
packages/svg-icons/src/chevron-down.svg
packages/svg-icons/src/chevron-up.svg
packages/svg-icons/src/index.ts
tests/__mocks__/fileMock.ts

This update addresses the need for a customizable and reusable expandable panel components in the project.

feat: expandablePanel component

---

.stylelintrc.json
packages/components/grid/README.md
packages/components/grid/package.json
packages/components/grid/src/Grid.stories.tsx
packages/components/grid/src/Grid.tsx
packages/components/grid/src/__tests__/Grid.spec.tsx
packages/components/grid/src/grid.styles.ts
packages/components/grid/src/grid.types.ts
packages/components/grid/src/index.ts
packages/components/grid/tsconfig.json
packages/components/grid/tsconfig.release.json
packages/components/grid/vite.config.ts
tsconfig.json

This component aims to be the design system grid component

feat: grid component

---

packages/components/grid/package.json
scripts/dui/templates/component/package.json

Update the package.json versioning in the DUI template to prevent CI-related issues with package resolution.

fix: update script version

---

packages/components/textarea/src/Textarea.stories.tsx

test: textarea ui tests

---

packages/components/grid/src/Grid.stories.tsx

This pr includes ui tests for grid component.

test: grid ui tests

---

packages/components/input/src/Input.stories.tsx

This PR implements input ui tests.

test: input ui tests

---

packages/components/video/README.md
packages/components/video/package.json
packages/components/video/src/Video.stories.tsx
packages/components/video/src/Video.tsx
packages/components/video/src/__tests__/Video.spec.tsx
packages/components/video/src/index.ts
packages/components/video/src/video.styles.ts
packages/components/video/src/video.types.ts
packages/components/video/tsconfig.json
packages/components/video/tsconfig.release.json
packages/components/video/vite.config.ts

This update addresses the need for a customizable and reusable set of a video component in the project.

feat: video component

---

packages/components/carousel/src/carousel.stories.ts

This pr adds tests for carousel component.

test: carousel ui tests

---

packages/components/typography/src/hooks/__tests__/useTypography.spec.tsx
packages/components/typography/src/hooks/index.ts
packages/components/typography/src/hooks/useTypography.tsx
packages/components/typography/src/typoTypes/body/Body1.tsx
packages/components/typography/src/typoTypes/body/Body2.tsx
packages/components/typography/src/typoTypes/body/Body3.tsx
packages/components/typography/src/typoTypes/body/Body4.tsx
packages/components/typography/src/typoTypes/body/Body5.tsx
packages/components/typography/src/typoTypes/body/Body6.tsx
packages/components/typography/src/typoTypes/display/Display1.tsx
packages/components/typography/src/typoTypes/display/Display2.tsx
packages/components/typography/src/typoTypes/display/Display3.tsx
packages/components/typography/src/typoTypes/display/Display4.tsx
packages/components/typography/src/typoTypes/display/Display5.tsx
packages/components/typography/src/typoTypes/display/Display6.tsx
packages/components/typography/src/typoTypes/heading/Heading1.tsx
packages/components/typography/src/typoTypes/heading/Heading2.tsx
packages/components/typography/src/typoTypes/heading/Heading3.tsx
packages/components/typography/src/typoTypes/heading/Heading4.tsx
packages/components/typography/src/typoTypes/heading/Heading5.tsx
packages/components/typography/src/typoTypes/heading/Heading6.tsx
packages/components/typography/src/utils/__tests__/getResponsiveTypography.spec.tsx
packages/components/typography/src/utils/getResposiveTypography.ts
packages/components/typography/src/utils/index.ts
packages/react/src/hooks/index.ts
packages/react/src/utils/__tests__/getWindowSize.spec.tsx
packages/react/src/utils/getWindowSize.ts
packages/react/src/utils/index.ts
tests/__mocks__/theme.ts

A small fix to avoid react package issues

fix: utils path and change the typography hook and util

---

packages/components/video/src/Video.stories.tsx

This is a bug fix for video component

fix: video component

---

packages/components/video/src/Video.stories.tsx
packages/components/video/src/Video.tsx

This pr adds tests for video component.
Also adds a data-testid for video component.

test: video ui tests

---

packages/components/expandable-panel/README.md
packages/components/expandable-panel/package.json
packages/components/expandable-panel/src/ExpandablePanel.stories.tsx
packages/components/expandable-panel/src/ExpandablePanel.tsx
packages/components/expandable-panel/src/__tests__/ExpandablePanel.spec.tsx
packages/components/expandable-panel/src/expandablePanel.styles.ts
packages/components/expandable-panel/src/expandablePanel.types.ts
packages/components/expandable-panel/src/expandablePanelTypes/ExpandablePanelBody.tsx
packages/components/expandable-panel/src/expandablePanelTypes/ExpandablePanelHeader.tsx
packages/components/expandable-panel/src/expandablePanelTypes/ExpandablePanelItem.tsx
packages/components/expandable-panel/src/expandablePanelTypes/index.ts
packages/components/expandable-panel/src/hooks/__tests__/useHandleToggle.spec.tsx
packages/components/expandable-panel/src/hooks/index.ts
packages/components/expandable-panel/src/hooks/useHandleToggle.ts

This update addresses the update of the expandable panel component in the project.

feat: expandable panel component update

---

packages/components/modal/README.md
packages/components/modal/package.json
packages/components/modal/src/Modal.stories.tsx
packages/components/modal/src/Modal.tsx
packages/components/modal/src/__tests__/Modal.spec.tsx
packages/components/modal/src/index.ts
packages/components/modal/src/modal.styles.ts
packages/components/modal/src/modal.types.ts
packages/components/modal/src/modalTypes/ModalFooter.tsx
packages/components/modal/src/modalTypes/ModalHeader.tsx
packages/components/modal/src/modalTypes/index.ts
packages/components/modal/tsconfig.json
packages/components/modal/tsconfig.release.json
packages/components/modal/vite.config.ts
packages/svg-icons/src/close.svg
packages/svg-icons/src/index.ts

This update addresses the need for a customizable and reusable set of a modal component in the project.

feat: modal component

---

packages/components/expandable-panel/src/ExpandablePanel.stories.tsx

This PR updates the tests for expandable panel.

test: update expandable tests

---

packages/components/toaster/README.md
packages/components/toaster/package.json
packages/components/toaster/src/Toaster.stories.tsx
packages/components/toaster/src/Toaster.tsx
packages/components/toaster/src/ToasterProvider.tsx
packages/components/toaster/src/ToasterStack.tsx
packages/components/toaster/src/__tests__/Toaster.spec.tsx
packages/components/toaster/src/customOptions/CloseButton.tsx
packages/components/toaster/src/customOptions/ProgressBar.tsx
packages/components/toaster/src/customOptions/customOptions.styles.ts
packages/components/toaster/src/customOptions/customOptions.types.ts
packages/components/toaster/src/customOptions/index.ts
packages/components/toaster/src/hooks/index.ts
packages/components/toaster/src/hooks/useToaster.ts
packages/components/toaster/src/hooks/useToasterQueue.tsx
packages/components/toaster/src/index.ts
packages/components/toaster/src/toaster.styles.ts
packages/components/toaster/src/toaster.types.ts
packages/components/toaster/src/toasterTypes/ErrorToaster.tsx
packages/components/toaster/src/toasterTypes/InfoToaster.tsx
packages/components/toaster/src/toasterTypes/SuccessToaster.tsx
packages/components/toaster/src/toasterTypes/WarningToaster.tsx
packages/components/toaster/src/toasterTypes/index.ts
packages/components/toaster/src/utils/getToasterTypesStyles.tsx
packages/components/toaster/src/utils/index.ts
packages/components/toaster/tsconfig.json
packages/components/toaster/tsconfig.release.json
packages/components/toaster/vite.config.ts

This update addresses the need for a customizable and reusable set of a toaster component in the project.

feat: toaster component

---

packages/components/avatar/README.md
packages/components/avatar/src/Avatar.stories.tsx
packages/components/avatar/src/Avatar.tsx
packages/components/avatar/src/__tests__/Avatar.spec.tsx
packages/components/avatar/src/avatar.styles.ts

This update addresses the requested feature for tag options on the avatar component in the project, unit test coverage, and the README update.

feat: avatar tag enhancement

---

.github/workflows/deploy.yml

This is a configuration to automatically deploy on netlify.

ci: deploy netlify

---

.github/workflows/deploy.yml

ci: fix build on deploy

---

.github/workflows/deploy.yml

ci: build fix

---

.github/workflows/deploy.yml
package.json
yarn.lock

fix: build

---

packages/components/tooltip/README.md
packages/components/tooltip/package.json
packages/components/tooltip/src/Tooltip.stories.tsx
packages/components/tooltip/src/Tooltip.tsx
packages/components/tooltip/src/__tests__/Tooltip.spec.tsx
packages/components/tooltip/src/hooks/__tests__/useClickOutside.spec.tsx
packages/components/tooltip/src/hooks/__tests__/useTooltipVisibility.spec.tsx
packages/components/tooltip/src/hooks/index.ts
packages/components/tooltip/src/hooks/useClickOutside.ts
packages/components/tooltip/src/hooks/useTooltipVisibility.ts
packages/components/tooltip/src/index.ts
packages/components/tooltip/src/tooltip.styles.ts
packages/components/tooltip/src/tooltip.types.ts
packages/components/tooltip/src/utils/__tests__/getPosition.spec.tsx
packages/components/tooltip/src/utils/__tests__/handleEvents.spec.tsx
packages/components/tooltip/src/utils/getPosition.ts
packages/components/tooltip/src/utils/handleEvents.ts
packages/components/tooltip/src/utils/index.ts
packages/components/tooltip/tsconfig.json
packages/components/tooltip/tsconfig.release.json
packages/components/tooltip/vite.config.ts

This update addresses the need for a customizable and reusable set of a tooltip component in the project.

feat: tooltip component

---

packages/components/dropdown/README.md
packages/components/dropdown/package.json
packages/components/dropdown/src/Dropdown.stories.tsx
packages/components/dropdown/src/Dropdown.tsx
packages/components/dropdown/src/__tests__/Dropdown.spec.tsx
packages/components/dropdown/src/dropdown.styles.ts
packages/components/dropdown/src/dropdown.types.ts
packages/components/dropdown/src/index.ts
packages/components/dropdown/tsconfig.json
packages/components/dropdown/tsconfig.release.json
packages/components/dropdown/vite.config.ts

This update addresses the need for a customizable and reusable set of a dropdown component in the project.

feat: dropdown component

---

packages/components/radio/README.md
packages/components/timeline/README.md
packages/components/timeline/package.json
packages/components/timeline/src/Timeline.stories.tsx
packages/components/timeline/src/Timeline.tsx
packages/components/timeline/src/TimelineGroup.tsx
packages/components/timeline/src/__tests__/Timeline.spec.tsx
packages/components/timeline/src/__tests__/TimelineGroup.spec.tsx
packages/components/timeline/src/index.ts
packages/components/timeline/src/timeline.styles.ts
packages/components/timeline/src/timeline.types.ts
packages/components/timeline/tsconfig.json
packages/components/timeline/tsconfig.release.json
packages/components/timeline/vite.config.ts

This update addresses the need for a customizable and reusable set of a timeline component in the project.

feat: timeline component

---

packages/components/toaster/src/customOptions/ProgressBar.tsx

This update addresses the need for a accessibility fix set of  toaster component in the project.

fix: toaster accessibility

---

packages/components/tags/src/tagTypes/DismissibleTag.tsx
packages/components/tags/src/tagTypes/ReadonlyTag.tsx
packages/components/tags/src/tagTypes/SelectableTag.tsx
packages/components/tags/src/tags.styles.ts
packages/components/tags/src/tags.types.ts

This update addresses the need for a customizable and reusable set of tags component in the project.

refactor: tags component

---

.husky/post-checkout
install-dependencies.js

This update introduces a script that automates the installation of Yarn dependencies whenever a branch switch occurs

feat: automate yarn dependency installation on branch checkout

---

jest.config.js
packages/components/radio/README.md
packages/components/radio/src/Radio.tsx
packages/components/radio/src/RadioGroup.stories.tsx
packages/components/radio/src/RadioGroup.tsx
packages/components/radio/src/__tests__/Radio.spec.tsx
packages/components/radio/src/__tests__/RadioGroup.spec.tsx
packages/components/radio/src/radio.styles.ts
packages/components/radio/src/radio.types.ts
packages/components/tooltip/README.md

This update addresses the need for a customizable and reusable set of radio component in the project.

refactor: radio component

---

jest.config.js
packages/components/expandable-panel/src/expandablePanelTypes/ExpandablePanelBody.tsx
packages/components/expandable-panel/src/expandablePanelTypes/ExpandablePanelHeader.tsx
packages/react/src/theme/theme.ts
packages/react/src/theme/theme.types.ts
packages/react/src/tokens/palettes/PaletteStory.tsx
packages/react/src/tokens/spacing/README.md
packages/react/src/tokens/spacing/SpacingStory.styles.tsx
packages/react/src/tokens/spacing/index.ts
packages/react/src/tokens/spacing/spacing.stories.tsx
packages/react/src/tokens/spacing/spacing.ts
packages/react/src/tokens/typography/TypoStory.styles.tsx

This update addresses the need for a spacing token in the project.

feat: spacing token

---

packages/components/dropdown/src/Dropdown.stories.tsx

test: dropdown tests

---

packages/components/breadcrumb/README.md
packages/components/breadcrumb/src/Breadcrumb.tsx
packages/components/breadcrumb/src/BreadcrumbGroup.stories.tsx
packages/components/breadcrumb/src/BreadcrumbGroup.tsx
packages/components/breadcrumb/src/__tests__/BreadcrumbGroup.spec.tsx
packages/components/breadcrumb/src/breadcrumb.styles.ts
packages/components/breadcrumb/src/breadcrumb.types.ts
packages/components/dropdown/README.md
packages/react/src/tokens/spacing/README.md

This update addresses the need for a customizable and reusable set of breadcrumb component in the project.

refactor: breadcrumb component

---

packages/components/modal/src/Modal.stories.tsx

test: storybook modal ui tests

---

packages/components/icon/src/Icon.stories.tsx
packages/components/icon/src/Icon.tsx

test: storybook icon ui tests

---

packages/components/tags/src/Tags.stories.tsx
packages/components/tags/src/Tags.tsx

test: storybook tags ui tests

---

.stylelintrc.json
packages/components/icon/README.md
packages/components/icon/src/Icon.stories.tsx
packages/components/icon/src/Icon.tsx
packages/components/icon/src/__tests__/Icon.spec.tsx
packages/components/icon/src/icon.styles.ts
packages/components/icon/src/icon.types.ts
packages/components/link/README.md
packages/components/link/package.json
packages/components/link/src/Link.stories.tsx
packages/components/link/src/Link.tsx
packages/components/link/src/__tests__/Link.spec.tsx
packages/components/link/src/link.styles.ts
packages/components/link/src/link.types.ts

This update addresses the need for a customizable and reusable set of link component in the project.

refactor: link component

---

packages/components/avatar/src/Avatar.stories.tsx
packages/components/avatar/src/AvatarGroup.stories.tsx
packages/components/badge/README.md
packages/components/badge/package.json
packages/components/badge/src/Badge.stories.tsx
packages/components/badge/src/Badge.tsx
packages/components/badge/src/__tests__/Badge.spec.tsx
packages/components/badge/src/badge.styles.ts
packages/components/badge/src/badge.types.ts
packages/components/badge/src/badgeTypes/AlertBadge.tsx
packages/components/badge/src/badgeTypes/IconBadge.tsx
packages/components/badge/src/badgeTypes/SuccessBadge.tsx
packages/components/badge/src/badgeTypes/WarningBadge.tsx
packages/components/badge/src/badgeTypes/index.ts
packages/components/button/README.md
packages/components/button/src/button.types.ts
packages/components/link/src/Link.stories.tsx
packages/components/link/src/link.types.ts
packages/components/radio/src/RadioGroup.stories.tsx
packages/components/tags/src/tags.types.ts
packages/components/toggle/src/Toggle.stories.tsx
packages/components/toggle/src/toggle.styles.ts
packages/components/toggle/src/toggle.types.ts
packages/svg-icons/src/ChevronDownIcon.tsx
packages/svg-icons/src/ChevronUpIcon.tsx
packages/svg-icons/src/CloseIcon.tsx
packages/svg-icons/src/StarIcon.tsx

This update addresses the need for a customizable and reusable set of badge component in the project.

refactor: badge component

---

packages/components/breadcrumb/src/BreadcrumbGroup.stories.tsx

test: storybook breadcrumb tests

---

packages/components/tooltip/src/Tooltip.stories.tsx

test: storybook tooltip tests

---

packages/components/textarea/README.md
packages/components/textarea/src/Textarea.stories.tsx
packages/components/textarea/src/Textarea.tsx
packages/components/textarea/src/__tests__/Textarea.spec.tsx
packages/components/textarea/src/textarea.styles.ts
packages/components/textarea/src/textarea.types.ts

This update addresses the need for a customizable and reusable set of textarea component in the project.

refactor: textarea component

---

packages/react/src/context/GlobalStyles.tsx

This update addresses the need for default styles by implementing global CSS with Emotion

fix: global styles

---

packages/components/tooltip/src/Tooltip.stories.tsx
packages/components/typography/src/Typography.stories.tsx

Adds tests for the typography component.

test: storybook ui typography tests

---

packages/components/toggle/src/Toggle.stories.tsx

This prs adds tests for toogle with icon component.

test: storybook ui tests toogle with icon

---

packages/components/link/src/Link.stories.tsx

This pr adds tests for the link inline.

test: storybook ui tests link inline

---

packages/react/src/hooks/__tests__/useViewport.spec.ts
packages/react/src/hooks/index.ts
packages/react/src/hooks/useViewport.ts

This PR adds a hook to check which breakpoint is active.

feat(react): add viewport hook

---

package.json
yarn.lock

Push dependencies to fix security issues.

chore(deps): push dependencies

---

.github/workflows/create-release-pr.yml
.github/workflows/deploy.yml
.github/workflows/ui-tests.yml

chore: add permissions workflows

---

packages/components/expandable-panel/src/ExpandablePanel.stories.tsx
packages/components/expandable-panel/src/ExpandablePanel.tsx
packages/components/expandable-panel/src/expandablePanel.types.ts
packages/components/expandable-panel/src/expandablePanelTypes/ExpandablePanelItem.tsx

This is an update of the expandable panel component

refactor: expandable panel

---

packages/components/avatar/src/avatar.styles.ts

This update addresses the change on the mix-blend-mode on AvatarFilter component in the project.

style: avatarFilter mix-blend-mode change

---

packages/components/breadcrumb/src/index.ts
packages/components/link/src/Link.stories.tsx
packages/components/link/src/Link.tsx
packages/components/link/src/__tests__/Link.spec.tsx
packages/components/link/src/link.types.ts
packages/components/typography/src/typography.types.ts

- Export default Breadcrumb
- Link icons as ReactNode
- Fix import React package errors on Typography

feat: component errors

---

package.json
yarn.lock

Increase tar-fs from 3.0.6 to 3.0.8.

chore(deps): update tar-fs

---

packages/components/modal/src/Modal.tsx

fix: modal component

---

.github/workflows/deploy.yml

Add .bin to the github path so netlify will be available for the scripts

fix: netlify github actions

---

packages/components/dropdown/src/Dropdown.tsx
packages/components/dropdown/src/dropdown.types.ts

- className "opened" has been added to ul tag
- custom icon

fix: dropdown

---

packages/components/dropdown/src/Dropdown.tsx
packages/components/dropdown/src/dropdown.styles.ts

fix: ellipsis
